package com.minhaz.orders101.endpoints;


import com.minhaz.orders101.enums.OrderStatus;
import com.minhaz.orders101.interfaces.*;
import com.minhaz.orders101.models.Customer;
import com.minhaz.orders101.models.LineItem;
import com.minhaz.orders101.models.Order;
import jakarta.validation.Valid;
import jakarta.validation.ValidationException;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;

@Component
@Path("/orders")
@Consumes("application/json")
@Slf4j
public class OrdersEndpoint {

  @Autowired
  private OrderDao dao;

  @Autowired
  private AddressDao addressDao;

  @Autowired
  private CustomerDao customerDao;

  @Autowired
  private LineItemDao lineItemDao;

  @Autowired
  private BasketDao basketDao;


  @POST
  public Response saveOrder(@Valid Order myOrder) throws ServerErrorException {
    log.info("Post method called with order details{}", myOrder);
    // TODO Remove the validation on the ID
    // TODO Make the ID column auto generated by the database

    addressDao.save(myOrder.getDeliveryAddress());
    customerDao.save(myOrder.getCustomer());
    lineItemDao.saveAll(myOrder.getBasket().getLineItems());
    basketDao.save(myOrder.getBasket());

    dao.save(myOrder);
    return Response.ok().build();
  }

  @GET
  @Produces({"application/json"})
  public Response getOrders() {
    List<Order> orders = dao.findAll();
    if (orders.isEmpty()) {
      return Response.status(Response.Status.NOT_FOUND).build();
    } else {
      return Response.ok().entity(orders).build();
    }
  }

  @PATCH
  public Response updateDate(Order myOrder) {
    // TODO Do something with the order
    Optional<Order> foundOrder = dao.findById("1");
    if (foundOrder.isPresent()) {
      Order order = foundOrder.get();
      log.info("Found the order with total price {}", order.getTotalPrice());
      // TODO Compare the input with the stored order. Find out what's changed and update it (look for java library to
      // compare two objects)
      order.setOrderStatus(OrderStatus.COMPLETED);
      dao.save(order);
    }
    return Response.ok().build();
  }

  @DELETE
  public Response deleteOrder(Order myOrder) {
    log.info("Delete method called on order {}", myOrder);
    dao.deleteById("1");
    return Response.ok().build();
  }

  @GET
  @Path("/{orderId}")
  @Produces({"application/json"})
  public Response getOrder(@PathParam("orderId") String orderId) {
    Optional<Order> order;
    order = dao.findById(orderId);
    if (order.isPresent()) {
      log.info("Get method called to retrieve order with ID = {}. Order details {}", order.get().getOrderId(), order);
      return Response.ok().entity(order).build();
    } else {
      return Response.status(Response.Status.NOT_FOUND).build();
    }
  }
}
